FROM apache/airflow:2.8.3-python3.10

COPY requirements.txt /requirements.txt
RUN pip install --no-cache-dir -r /requirements.txt

COPY dags /opt/airflow/dags
COPY plugins /opt/airflow/plugins
COPY config /opt/airflow/config
COPY CineRecomender /opt/airflow/CineRecomender

ENV CINE_RECOMMENDER_PATH=/opt/airflow/CineRecomender

ENTRYPOINT ["/entrypoint"]

CMD ["webserver"]