FROM apache/airflow:2.8.3-python3.10

COPY requirements.txt /requirements.txt
RUN pip install --no-cache-dir -r /requirements.txt

COPY dags /opt/airflow/dags

ENTRYPOINT ["/entrypoint"]

CMD ["webserver"]